---
- hosts: all
  tasks:
    - name: Content update
      copy:
        dest: /tmp/resolv.conf
        content: "nameserver 192.168.1.1\n"

    - name: Instala VIM RedHat
      dnf:
        name: vim
        state: latest
      when: ansible_facts['os_family']| lower == 'redhat'

    - name: Instala VIM Debian
      apt:
        name: vim
        state: latest
      when: ansible_facts['os_family']| lower == 'debian'
...

