---
- hosts: all 
  gather_facts: yes 
  become: true
    #  user: oze
  pre_tasks:
    - name: Muestra familia SO
      debug:
        msg: "Familia es: {{ ansible_facts['os_family'] }}"
  roles: 
    - update
...
